### ISSUE TITLE
Client error log related to Minotaurs

### ISSUE THREAD

**Issue by theron61** [Silentine/GrimoireOfGaia#122]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.5.2815
* Mod Version: 1.6.9.3
* Java Version: 1.8.0.201 (64-bit)

## Issue Description

Getting this spammed randomly in the client log when around minotauresses (which are invisible):

[19:41:08] [Client thread/ERROR] [minecraft/RenderLivingBase]: Couldn't render entity
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at gaia.entity.monster.EntityGaiaMinotaurus.getTextureType(EntityGaiaMinotaurus.java:234) ~[EntityGaiaMinotaurus.class:?]
	at gaia.renderer.entity.RenderGaiaMinotaurus.getTexture(RenderGaiaMinotaurus.java:40) ~[RenderGaiaMinotaurus.class:?]
	at gaia.renderer.entity.RenderGaiaMinotaurus.getEntityTexture(RenderGaiaMinotaurus.java:36) ~[RenderGaiaMinotaurus.class:?]
	at gaia.renderer.entity.RenderGaiaMinotaurus.func_110775_a(RenderGaiaMinotaurus.java:15) ~[RenderGaiaMinotaurus.class:?]
	at net.minecraft.client.renderer.entity.Render.func_180548_c(Render.java:127) ~[bzg.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_77036_a(RenderLivingBase.java:334) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:240) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:16) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:839) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1800) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[19:41:08] [Client thread/ERROR] [minecraft/RenderLivingBase]: Couldn't render entity
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at gaia.entity.monster.EntityGaiaMinotaurus.getTextureType(EntityGaiaMinotaurus.java:234) ~[EntityGaiaMinotaurus.class:?]
	at gaia.renderer.entity.RenderGaiaMinotaurus.getTexture(RenderGaiaMinotaurus.java:40) ~[RenderGaiaMinotaurus.class:?]
	at gaia.renderer.entity.RenderGaiaMinotaurus.getEntityTexture(RenderGaiaMinotaurus.java:36) ~[RenderGaiaMinotaurus.class:?]
	at gaia.renderer.entity.RenderGaiaMinotaurus.func_110775_a(RenderGaiaMinotaurus.java:15) ~[RenderGaiaMinotaurus.class:?]
	at net.minecraft.client.renderer.entity.Render.func_180548_c(Render.java:127) ~[bzg.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_77036_a(RenderLivingBase.java:334) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:240) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:16) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412) [bzf.class:?]

**Comment by tristanpoland** [comment]
having a similar issue to this still version 1.12.2, what mods are you using?

**Comment by Mrbysco** [comment]
Are any of you using Optifine? and if so can you reproduce the issue without?
