### ISSUE TITLE
help command error

### ISSUE THREAD

**Issue by Tarod7** [Silentine/GrimoireOfGaia#38]
[18:52:05] [Server thread/WARN]: Couldn't process command: 'help'
java.lang.NullPointerException
        at gaia.util.GaiaICommand.func_184882_a(GaiaICommand.java:399) ~[GaiaICommand.class:?]
        at com.feed_the_beast.ftbu.ranks.Ranks.checkCommandPermission(Ranks.java:239) ~[Ranks.class:?]
        at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184882_a(CmdOverride.java:65) ~[CmdOverride.class:?]
        at net.minecraft.command.CommandHandler.func_71557_a(CommandHandler.java:198) ~[k.class:?]
        at com.matthewprenger.helpfixer.HelpFixer$1.func_184900_a(HelpFixer.java:40) ~[HelpFixer$1.class:1.4.15]
        at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:73) ~[al.class:?]
        at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:59) ~[CmdOverride.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

I think there's a help command not implemented correctly. I tried using the helpfixer mod to fix it but it didn't work.

**Comment by Silentine** [comment]
I believe this is fixed in the **1.5.5** version of this mod.

Credit goes to **combusterf** for the fix.
